### PR TITLE
Mongo database adapter

### PR DESCRIPTION
**Pull request by mtorchio**
This pull request adds a new IDataSource called MongoDataSource and instructions to installing MongoDB and inserting the hard-coded patient data.

### CODE REVIEW

**Comment by jafeltra** [comment]
[JA1] I think the insertHardCodedPatient.js script should exit once it's done inserting. I think this can be accomplished by adding `process.exit()` after the console.log line that says how many items were inserted.

[JA2] Since we had to remove the autogenerated `res.end()` line in the DefaultService.js file, I think we should update the readme and the instructions to specify replacing that line rather than just adding in our additional line on top of it. 

[JA3] I think the MongoDataSource.js file can be moved into the dataaccess directory.

I can push changes to fix these three things if that's easiest. Other than that, it looks good to me! Nice job!

**Comment by gregquinn2001** [comment]
Good feedback!

**Comment by jafeltra** [comment]
I just pushed changes that fix JA1, JA2, and JA3. I think this PR should be set now! (at least from what I can tell).

**Comment by nicoleng12** [comment]
I updated the README to make instructions a bit more clear

**Comment by nicoleng12** [comment]
All the issues have been addressed. The instructions for installing and setting up mongo are clear and I was able to follow them successfully. This looks good on my end

**Review by nicoleng12 — APPROVED** [review]

**Review by jafeltra — APPROVED** [review]
Looks good with the changes made!

**Pull request merged**
