### PR TITLE
Updated hard coded patient SHR JSON to match what is in the Flux repo…

### PR DESCRIPTION
**Pull request by mtorchio**
…sitory. This is used to populate the Mongo database. Also edited setup script to remove any existing flux collection before inserting.

With this change, the current version of Flux has the new data it needs.

### CODE REVIEW

**Review by jafeltra — APPROVED** [review]
This looks good to me! /p2 in Flux Notes now renders without errors in the console. Dropping the collection first ensures we are only using the entries in the current hard coded patient.

**Comment by gregquinn2001** [comment]
Can we delete all entries for the demo patient id rather than all entries? That would allow this script to be run on an existing database without disrupting other patients but would still drop an existing instance of the demo patient and then add it.

**Comment by mtorchio** [comment]
That is a good idea Greg, I'll make that change.

**Comment by mtorchio** [comment]
Does it still make sense to merge this in with the changes we are making to the hard coded patient in Flux? I think we want to keep the changes in insertHardCodedPatient.js at least.

**Review by gregquinn2001 — APPROVED** [review]

**Pull request merged**
