### PR TITLE
Update server to use data access

### PR DESCRIPTION
**Pull request by nicoleng12**
Updated the server to use the data access layer to get patient information

- Added data access layer folder with  data access file and data sources to the server folder
- Removed unneeded data sources on the server side
- Moved flux implementation folder inside the server folder (babel was picky about file locations)
- Added babel to handle es6 to es5
- Running the server and navigating to http://localhost:3001/api/patient/-1

### CODE REVIEW

**Comment by mtorchio** [comment]
Thanks for adding this! Reading the source, it looks good. I will build on this by adding my own MongoDataSource and replace the HardCodedDataSource. But first, I'll run this code and test it so we can merge this in.

**Comment by nicoleng12** [comment]
Updated README at @jafeltra suggestion to note the change in directory locations

**Comment by gregquinn2001** [comment]
[GQ1] You can delete .testingbablerc right?

**Comment by gregquinn2001** [comment]
[GQ2] Let's add a JIRA to create a way to be able to configure the data source at deployment time. The HardCodedDataSource should not be removed, but it won't be used by default once we have the Mongo one.

**Comment by gregquinn2001** [comment]
[GQ3] Should we try to eliminate the node6 preset and the dependency for it?

**Comment by nicoleng12** [comment]
[GQ1] - deleted the file

[GQ2] - added a jira: https://jira.mitre.org/browse/ASCODCP-726

[GQ3] - I'll look into that right now

**Comment by nicoleng12** [comment]
[GQ3] - removed node6 dependency

**Review by gregquinn2001 — APPROVED** [review]

**Review by mtorchio — APPROVED** [review]

**Comment by jafeltra** [comment]
[JA1] I think that we can remove the HardCodedPatient.json file from the /fluxImplementation folder now that we've added it into the /dataaccess folder. I don't think it's even used anymore anyway.

**Comment by jafeltra** [comment]
Also, this is one commit behind so it should be rebased before being merged.

**Comment by jafeltra** [comment]
[JA2] This is really small, and I'm not even sure if it makes a difference, but should the DEMO_PATIENT_ID in the DataAccess.jsx return a string "-1" like it does in the DataAccess in the Flux repository?
[JA3] It looks like you change the package.json file within the nodejs-server-server file. I think I remember you saying Babel needed specific file structures, but that package.json was generated from the Swagger.yaml file. So we may want to note what we added somewhere. I haven't looked into what happens with the package.json file when you regenerate code using the swagger-codegen tool (which we aren't using yet).

**Comment by gregquinn2001** [comment]
For JA1, hard coded json patient should stay because we still have the data source in the project. Neither will be used typically, but they could be configured instead of using the new database one that Mike will introduce.

**Comment by gregquinn2001** [comment]
JA2 is an interesting question. I think maybe it should stay because all data sources should support the demo patient ID. To do so, they should use the constant defined in Data Access so if we change it, they are all updated. Does that make sense?

**Comment by gregquinn2001** [comment]
JA3 needs to be explored! Good call!

**Comment by gregquinn2001** [comment]
I misunderstood on JA1. Julia is absolutely right. We should remove the hard coded patient json from fluxImplementation!

**Comment by gregquinn2001** [comment]
For JA2, we should fix the DEMO PATIENT ID to be a string here like it is on the client side. A string containing -1. So Julia is correct, I think it should return "-1"; DataAccess.jsx line 5.

**Comment by jafeltra** [comment]
@nicoleng12  I can fix JA1 and JA2 and push changes if you agree with them. And we can talk about JA3 if you want to see what makes the most sense there.

**Comment by nicoleng12** [comment]
Addressed [JA1], [JA2], and [JA3]. For [JA3] i added documentation to the README to include the list of packages added to package.json. I also rebased the branch so it should be up to date with the latest version in master

**Comment by jafeltra** [comment]
Thanks Nicole! For JA3, Nicole and I talked about maybe seeing if it is possible to add a separate package.json file for the main shr-node-server project and including the babel required packages there instead of in the package.json that was autogenerated (the one inside nodejs-server-server). This would mean the file structure would look something like:
-shr-node-server
             - README.md - the one we created, contains our changes, etc
        - package.json - contains the packages we need for babel
        - nodejs-server-server - autogenerated code with readme and package.json file we don’t touch
        - the flux specific files - at the same level as the autogenerated code instead of inside it.

I'm not sure if this would work or not, but if it did I think it would let us keep the package.json that was autogenerated the same so there is less code we'd have to worry about transitioning over/saving if we regenerated the server. @gregquinn2001 do you have any thoughts on this approach? Does that seem like something that would make sense to investigate? Should it be a separate Jira issue since Nicole's code works as it is now and this would require more work?

**Comment by gregquinn2001** [comment]
sounds worth exploring! Go ahead and see if it works, but I wouldn't spend too much time fighting with it if it doesn't.

**Comment by nicoleng12** [comment]
@gregquinn2001 @jafeltra  I updated the folder structure. It works on my end. Can you guys make sure it works on your end too? I updated the README to reflect the folder structure changes

**Comment by jafeltra** [comment]
All the changes make sense to me and I pulled it and can run it successfully! Looks good to me! I'll merge it now!

**Review by jafeltra — APPROVED** [review]

**Pull request merged**
